=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000011-ENA.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.ebi.ac.uk/biosamples/schemas/ENA-ENA_default_sample_checklist/1.0.0",
  "title": "ENA default sample checklist",
  "description": "Minimum information required for the sample",
  "definitions": {
    "externalAccession": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "xrefLink": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "urlLink": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "identifiers": {
      "type": "object",
      "properties": {
        "externalAccessions": {
          "type": "array",
          "$ref": "#/definitions/externalAccession"
        },
        "secondaryAccessions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "organism": {
      "type": "object",
      "properties": {
        "taxonId": {
          "type": "string"
        },
        "commonName": {
          "type": "string"
        },
        "scientificName": {
          "type": "string"
        },
        "anonymizedName": {
          "type": "string"
        },
        "individualName": {
          "type": "string"
        }
      }
    },
    "attribute": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        }
      }
    },
    "link": {
      "type": "object",
      "properties": {
        "xrefLink": {
          "$ref": "#/definitions/xrefLink"
        },
        "urlLink": {
          "$ref": "#/definitions/urlLink"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "alias": {
      "type": "string"
    },
    "accession": {
      "type": "string"
    },
    "identifiers": {
      "$ref": "#/definitions/identifiers"
    },
    "centerName": {
      "type": "string"
    },
    "brokerName": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "organism": {
      "$ref": "#/definitions/organism"
    },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tag": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }, "unit": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "tag",
          "value"
        ],
        "allOf": [
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "collection date"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "type": "string",
                  "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "geographic location"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "enum": [
                    "UK",
                    "UGANDA"
                  ]
                }
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "type": "object",
            "description": "The date the sample was collected with the intention of sequencing, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid ISO8601 compliant times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008.",
            "properties": {
              "tag": {
                "enum": [
                  "collection date",
                  "Event Date/Time",
                  "collection_date"
                ]
              },
              "value": {
                "type": "string",
                "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)"
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "tag",
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "tag": {
                "enum": [
                  "geographic location"
                ]
              }
            },
            "required": [
              "tag"
            ]
          },
          "then": {
            "properties": {
              "value": {
                "enum": [
                  "UK",
                  "UGANDA"
                ]
              },
              "unit": {
                "type": "string"
              }
            }
          }
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/link"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "alias",
    "accession",
    "organism",
    "attributes"
  ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000027
/SAMEA8667463.json
{
  "alias" : "SI003-028_18S",
  "accession" : "ERS6351992",
  "centerName" : "MATIS OHF.",
  "title" : "Icelandic seawater",
  "description" : "2014-05-17_SI3_290_20m",
  "organism" : {
    "taxonId" : "408172",
    "commonName" : "marine metagenome",
    "scientificName" : "marine metagenome"
  },
  "attributes" : [ {
    "tag" : "Depth",
    "value" : "20",
    "unit" : "m"
  }, {
    "tag" : "environment (biome)",
    "value" : "ENVO:00000447"
  }, {
    "tag" : "environment (feature)",
    "value" : "ENVO:00002149"
  }, {
    "tag" : "environment (material)",
    "value" : "ENVO:00002010"
  }, {
    "tag" : "environmental package",
    "value" : "water"
  }, {
    "tag" : "Event Date/Time",
    "value" : "2014-05-17T21:00:00Z/2014-05-17T21:17:00Z"
  }, {
    "tag" : "Latitude Start",
    "value" : "66.5436",
    "unit" : "DD"
  }, {
    "tag" : "Longitude Start",
    "value" : "-18.8442",
    "unit" : "DD"
  }, {
    "tag" : "Marine Region",
    "value" : "North Atlantic Ocean"
  }, {
    "tag" : "project name",
    "value" : "MIME"
  }, {
    "tag" : "Protocol Label",
    "value" : "NPL022"
  }, {
    "tag" : "Salinity",
    "value" : "35.0273",
    "unit" : "psu"
  }, {
    "tag" : "Sampling Campaign",
    "value" : "B4-2014"
  }, {
    "tag" : "Sampling Platform",
    "value" : "Research Vessel Bjarni Saemundsson"
  }, {
    "tag" : "Sampling Site",
    "value" : "SI3"
  }, {
    "tag" : "Temperature",
    "value" : "6.1955",
    "unit" : "ÂºC"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000027"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000023
/SAMEA111476875.json
{
  "alias" : "AEST.32",
  "accession" : "ERS13570911",
  "centerName" : "TU Delft",
  "title" : "Beverwijk-Ca-1-t24",
  "description" : "-",
  "organism" : {
    "taxonId" : "412754",
    "scientificName" : "bioreactor sludge metagenome"
  },
  "attributes" : [ {
    "tag" : "broad-scale environmental context",
    "value" : "anthropogenic environmental material (ENVO:0010001)"
  }, {
    "tag" : "collection date",
    "value" : "2021-03-15"
  }, {
    "tag" : "condition",
    "value" : "CALCIUM"
  }, {
    "tag" : "day",
    "value" : "20210315"
  }, {
    "tag" : "description",
    "value" : "AEST.32"
  }, {
    "tag" : "environmental medium",
    "value" : "secondary sludge (ENVO:00002058)"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Netherlands"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "52.47368",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "4.66736",
    "unit" : "DD"
  }, {
    "tag" : "local environmental context",
    "value" : "activated sludge (ENVO:00002046)"
  }, {
    "tag" : "project name",
    "value" : "Calcium enhances PHA production and selective growth"
  }, {
    "tag" : "replicate",
    "value" : "A"
  }, {
    "tag" : "sequencing method",
    "value" : "Illumina MiSeq"
  }, {
    "tag" : "time",
    "value" : "T24"
  }, {
    "tag" : "wwtp",
    "value" : "BEVERWIJK"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000023"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000050
/SAMEA112264529.json
{
  "alias" : "ERR4918427_bin.2_MetaWRAP_v1.1_bin",
  "accession" : "ERS14375384",
  "centerName" : "UNIVERSITY OF COPENHAGEN",
  "title" : "Binned metagenome: ERR4918427_bin.2_MetaWRAP_v1.1_bin",
  "description" : "This sample represents a binned metagenome assembled from the metagenomic run ERR4918427 of study ERP125469.",
  "organism" : {
    "taxonId" : "1378299",
    "commonName" : "",
    "scientificName" : "Photobacterium piscicola"
  },
  "attributes" : [ {
    "tag" : "taxonomic classification",
    "value" : "The taxonomy of this binned metagenome was originally computed with GTDBtk, which assigned the following taxonomic annotation: d__Bacteria;p__Proteobacteria;c__Gammaproteobacteria;o__Vibrionales;f__Vibrionaceae;g__Photobacterium;s__Photobacterium piscicola"
  }, {
    "tag" : "project name",
    "value" : "HoloFood Salmon - Metagenome"
  }, {
    "tag" : "sequencing method",
    "value" : "DNBSEQ-G400"
  }, {
    "tag" : "assembly software",
    "value" : "metaSPAdes v3.14.1"
  }, {
    "tag" : "binning software",
    "value" : "MetaWRAP v1.1"
  }, {
    "tag" : "binning parameters",
    "value" : "MaxBin2, MetaBat2, Concoct with default parameter of the metaWRAP pipeline. Bin refinement module used from metaWRAP with default parameters."
  }, {
    "tag" : "completeness software",
    "value" : "CheckM"
  }, {
    "tag" : "completeness score",
    "value" : "59.57",
    "unit" : "%"
  }, {
    "tag" : "contamination score",
    "value" : "2.06",
    "unit" : "%"
  }, {
    "tag" : "isolation_source",
    "value" : "fish gut metagenome"
  }, {
    "tag" : "collection date",
    "value" : "2019-08-12"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Norway"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "66.0799",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "12.587848",
    "unit" : "DD"
  }, {
    "tag" : "broad-scale environmental context",
    "value" : "Salmon digestive system"
  }, {
    "tag" : "local environmental context",
    "value" : "Digestive tube"
  }, {
    "tag" : "environmental medium",
    "value" : "Gut"
  }, {
    "tag" : "sample derived from",
    "value" : "SAMEA7687898"
  }, {
    "tag" : "metagenomic source",
    "value" : "fish gut metagenome"
  }, {
    "tag" : "taxonomic identity marker",
    "value" : "multi-marker approach"
  }, {
    "tag" : "investigation type",
    "value" : "metagenome-assembled genome"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000050"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000024
/SAMEA110278118.json
{
  "alias" : "65906:f7084606-7f7a-47c4-b15a-ee4fb9d7b2a0",
  "accession" : "ERS12375732",
  "centerName" : "Alfred Wegener Institute Helmholtz Centre for Polar and Marine Research",
  "title" : "RAS_EGC_09_1920_1",
  "description" : "FRAM mooring EGC-6: microbial annual cycle 2019-20",
  "organism" : {
    "taxonId" : "1561972",
    "scientificName" : "seawater metagenome"
  },
  "attributes" : [ {
    "tag" : "locus_tag",
    "value" : "16S"
  }, {
    "tag" : "sample_description",
    "value" : "FRAM mooring EGC-6: microbial annual cycle 2019-20"
  }, {
    "tag" : "collection date",
    "value" : "2019-09-19"
  }, {
    "tag" : "geographic location (depth)",
    "value" : "66.55",
    "unit" : "m"
  }, {
    "tag" : "environmental package",
    "value" : "water"
  }, {
    "tag" : "sample collection device or method",
    "value" : "Remote Access Sampler"
  }, {
    "tag" : "sample material processing",
    "value" : "Sterivex_0.2um"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "78.99576667",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "-5.39633333",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Arctic Ocean"
  }, {
    "tag" : "geographic location (region and locality)",
    "value" : "Fram Strait"
  }, {
    "tag" : "environment (biome)",
    "value" : "marine biome [ENVO:00000447]"
  }, {
    "tag" : "environment (material)",
    "value" : "sea water [ENVO:00002149]"
  }, {
    "tag" : "environment (feature)",
    "value" : "microbial community [PCO:1000004]"
  }, {
    "tag" : "project name",
    "value" : "FRAM"
  }, {
    "tag" : "nucleic acid extraction",
    "value" : "PowerWater"
  }, {
    "tag" : "investigation type",
    "value" : "mimarks-survey"
  }, {
    "tag" : "pcr primers",
    "value" : "FWD:GTGYCAGCMGCCGCGGTAA REV:CCGYCAATTYMTTTRAGTTT; 515F-926R"
  }, {
    "tag" : "target subfragment",
    "value" : "V4-V5"
  }, {
    "tag" : "submitted to insdc",
    "value" : "true"
  }, {
    "tag" : "sequencing method",
    "value" : "Illumina MiSeq"
  }, {
    "tag" : "water environmental package",
    "value" : "water"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000024"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000044
/SAMEA8562865.json
{
  "alias" : "S15BD10196",
  "accession" : "ERS6247546",
  "centerName" : "Sciensano",
  "title" : "clinical sample Shigella sonnei",
  "description" : "faeces",
  "organism" : {
    "taxonId" : "624",
    "scientificName" : "Shigella sonnei"
  },
  "attributes" : [ {
    "tag" : "collected_by",
    "value" : "NRCSS Belgium at Sciensano"
  }, {
    "tag" : "collection_date",
    "value" : "2015-12-03"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Belgium"
  }, {
    "tag" : "host scientific name",
    "value" : "Home sapiens"
  }, {
    "tag" : "isolate",
    "value" : "clinical"
  }, {
    "tag" : "patient gender",
    "value" : "Male"
  }, {
    "tag" : "year",
    "value" : "2015"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000044"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000020
/SAMEA112162714.json
{
  "alias" : "T1RIBP4",
  "accession" : "ERS14272511",
  "centerName" : "UNIVERSITY OF BOLOGNA",
  "title" : "T1RIBP4",
  "description" : "Rhizosphere",
  "organism" : {
    "taxonId" : "29760",
    "commonName" : "wine grape",
    "scientificName" : "Vitis vinifera"
  },
  "attributes" : [ {
    "tag" : "broad-scale environmental context",
    "value" : "Vineyard"
  }, {
    "tag" : "collection date",
    "value" : "not collected"
  }, {
    "tag" : "environmental medium",
    "value" : "Soil"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Italy"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "44.82",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "11.06",
    "unit" : "DD"
  }, {
    "tag" : "local environmental context",
    "value" : "Rhizosphere"
  }, {
    "tag" : "project name",
    "value" : "PRJEB57815"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000020"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000036
/SAMEA10033111.json
{
  "alias" : "MQ210823-5",
  "accession" : "ERS7711315",
  "centerName" : "WDRC KAUST",
  "title" : "MABRbiofilm_cDNA_day75_feedWW&OMPspike_A1",
  "description" : "cDNA of MABR biofilm-Reactor A1 fed with wastewater and spiked with 13OMPs at 50ugL-1, sampled 23 April 2021",
  "organism" : {
    "taxonId" : "527639",
    "commonName" : "MABRbiofilm_cDNA_day75_feedWW&OMPspike_A1",
    "scientificName" : "wastewater metagenome"
  },
  "attributes" : [ {
    "tag" : "collection date",
    "value" : "2021-04-23"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Saudi Arabia"
  }, {
    "tag" : "investigation type",
    "value" : "metagenome"
  }, {
    "tag" : "sewage type",
    "value" : "Municipal wastewater treatment plant"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000036"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000036
/SAMEA4044474.json
{
  "alias" : "DTU2016-1144-PRJ1066-RL-Sewage-78_S12_L001",
  "accession" : "ERS1215584",
  "centerName" : "DTU",
  "title" : "Danish sewage",
  "organism" : {
    "taxonId" : "527639",
    "scientificName" : "wastewater metagenome"
  },
  "attributes" : [ {
    "tag" : "collection date",
    "value" : "2016-04-02"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Denmark"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "55.694986",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "12.615025999999943",
    "unit" : "DD"
  }, {
    "tag" : "investigation type",
    "value" : "metagenome"
  }, {
    "tag" : "name of the sampling site",
    "value" : "Renseanl√¶g Lynetten"
  }, {
    "tag" : "sewage type",
    "value" : "Waste water treatment plant"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000036"
  } ]
}
