=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000011-ENA.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.ebi.ac.uk/biosamples/schemas/ENA-ENA_default_sample_checklist/1.0.0",
  "title": "ENA default sample checklist",
  "description": "Minimum information required for the sample",
  "definitions": {
    "externalAccession": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "xrefLink": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "urlLink": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "identifiers": {
      "type": "object",
      "properties": {
        "externalAccessions": {
          "type": "array",
          "$ref": "#/definitions/externalAccession"
        },
        "secondaryAccessions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "organism": {
      "type": "object",
      "properties": {
        "taxonId": {
          "type": "string"
        },
        "commonName": {
          "type": "string"
        },
        "scientificName": {
          "type": "string"
        },
        "anonymizedName": {
          "type": "string"
        },
        "individualName": {
          "type": "string"
        }
      }
    },
    "attribute": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        }
      }
    },
    "link": {
      "type": "object",
      "properties": {
        "xrefLink": {
          "$ref": "#/definitions/xrefLink"
        },
        "urlLink": {
          "$ref": "#/definitions/urlLink"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "alias": {
      "type": "string"
    },
    "accession": {
      "type": "string"
    },
    "identifiers": {
      "$ref": "#/definitions/identifiers"
    },
    "centerName": {
      "type": "string"
    },
    "brokerName": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "organism": {
      "$ref": "#/definitions/organism"
    },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tag": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }, "unit": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "tag",
          "value"
        ],
        "allOf": [
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "collection date"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "type": "string",
                  "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "geographic location"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "enum": [
                    "UK",
                    "UGANDA"
                  ]
                }
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "type": "object",
            "description": "The date the sample was collected with the intention of sequencing, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid ISO8601 compliant times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008.",
            "properties": {
              "tag": {
                "enum": [
                  "collection date",
                  "Event Date/Time",
                  "collection_date"
                ]
              },
              "value": {
                "type": "string",
                "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)"
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "tag",
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "tag": {
                "enum": [
                  "geographic location"
                ]
              }
            },
            "required": [
              "tag"
            ]
          },
          "then": {
            "properties": {
              "value": {
                "enum": [
                  "UK",
                  "UGANDA"
                ]
              },
              "unit": {
                "type": "string"
              }
            }
          }
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/link"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "alias",
    "accession",
    "organism",
    "attributes"
  ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000030
/SAMEA111554041.json
{
  "alias" : "JC21-P4-5_S252_L001_R1_001",
  "accession" : "ERS13664092",
  "centerName" : "UNIVERSITY OF BERGEN/DEPT. OF BIOLOGY",
  "title" : "JC2_1_P4_0005m",
  "description" : "16S_amplicon_sequences_from_the_JC2_1_cruise_2021_Nansen_Legacy",
  "organism" : {
    "taxonId" : "1561972",
    "scientificName" : "seawater metagenome"
  },
  "attributes" : [ {
    "tag" : "broad-scale environmental context",
    "value" : "Barent's_Sea"
  }, {
    "tag" : "Depth",
    "value" : "5",
    "unit" : "m"
  }, {
    "tag" : "environmental medium",
    "value" : "water"
  }, {
    "tag" : "environmental package",
    "value" : "water"
  }, {
    "tag" : "Event Date/Time Start",
    "value" : "2021-07-18"
  }, {
    "tag" : "Latitude Start",
    "value" : "79.75",
    "unit" : "DD"
  }, {
    "tag" : "local environmental context",
    "value" : "Norwegian_Barent's_Sea_East_and_North_of_Svalbard"
  }, {
    "tag" : "Longitude Start",
    "value" : "34",
    "unit" : "DD"
  }, {
    "tag" : "Marine Region",
    "value" : "Norwegian_Barent's_Sea_East_and_North_of_Svalbard"
  }, {
    "tag" : "project name",
    "value" : "Nansen_Legacy_Summer"
  }, {
    "tag" : "Protocol Label",
    "value" : "UiB"
  }, {
    "tag" : "Salinity Sensor",
    "value" : "33.08",
    "unit" : "psu"
  }, {
    "tag" : "Sampling Campaign",
    "value" : "The_Nansen_Legacy_JC2-1"
  }, {
    "tag" : "Sampling Platform",
    "value" : "RV_Kronprins_Haakon"
  }, {
    "tag" : "Sampling Station",
    "value" : "P4"
  }, {
    "tag" : "Temperature",
    "value" : "-0.09",
    "unit" : "ÂºC"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000030"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000034
/SAMEA4081099.json
{
  "alias" : "2865_1_11SJK246-04",
  "accession" : "ERS1252209",
  "centerName" : "NETHERLANDS CANCER INSTITUTE",
  "title" : "2865_1_11SJK246-04",
  "description" : "11SJK246-04 - CLC tissue",
  "organism" : {
    "taxonId" : "10090",
    "commonName" : "house mouse",
    "scientificName" : "Mus musculus"
  },
  "attributes" : [ {
    "tag" : "tissue_type",
    "value" : "mammary tumor"
  }, {
    "tag" : "sex",
    "value" : "female"
  }, {
    "tag" : "diagnosis",
    "value" : "classic invasive lobular carcinoma"
  }, {
    "tag" : "strain",
    "value" : "Wcre;Cdh1F/F;PtenF/F (FVB)"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000034"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000035
/SAMEA112143749.json
{
  "alias" : "PS103.14-26_S_0_LL",
  "accession" : "ERS14253507",
  "centerName" : "University of Duisburg-Essen",
  "title" : "S_0_LL",
  "description" : "clonal cell culture",
  "organism" : {
    "taxonId" : "186038",
    "scientificName" : "Fragilariopsis kerguelensis"
  },
  "attributes" : [ {
    "tag" : "block",
    "value" : "genotype at a certain temperature light setting"
  }, {
    "tag" : "dev_stage",
    "value" : "exponential growth"
  }, {
    "tag" : "ecotype",
    "value" : "most southern sample station and thus coldest region of distribution area"
  }, {
    "tag" : "environmental stress",
    "value" : "illumination"
  }, {
    "tag" : "experimental factor 1",
    "value" : "genotype"
  }, {
    "tag" : "experimental factor 2",
    "value" : "temperature"
  }, {
    "tag" : "genotype",
    "value" : "SOUTH"
  }, {
    "tag" : "growth condition",
    "value" : "0°C, low light (15–30 µmol/m2s)"
  }, {
    "tag" : "replicate",
    "value" : "biological"
  }, {
    "tag" : "sampling time point",
    "value" : "between 4 and 6 hr after light on"
  }, {
    "tag" : "strain",
    "value" : "PS103.14-26"
  }, {
    "tag" : "time",
    "value" : "> one period of exponential growth"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000035"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000053
/SAMEA111556856.json
{
  "alias" : "27913",
  "accession" : "ERS13666902",
  "centerName" : "Tree of Life Programme",
  "title" : "27913-tol",
  "organism" : {
    "taxonId" : "2991509",
    "scientificName" : "Gordius sp. MW1"
  },
  "attributes" : [ {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000053"
  }, {
    "tag" : "organism part",
    "value" : "WHOLE ORGANISM"
  }, {
    "tag" : "lifestage",
    "value" : "adult"
  }, {
    "tag" : "project name",
    "value" : "ToL"
  }, {
    "tag" : "tolid",
    "value" : "tfGorSpea3"
  }, {
    "tag" : "collected_by",
    "value" : "LOUISE COATES | BEN MURCOTT"
  }, {
    "tag" : "collection date",
    "value" : "2022-09-29"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "United Kingdom"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "51.604",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "-2.295",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (region and locality)",
    "value" : "England | South West | Gloucestershire | Stroud | Midger Wood"
  }, {
    "tag" : "identified_by",
    "value" : "LOUISE COATES | VICKY HUNT"
  }, {
    "tag" : "habitat",
    "value" : "Shallow river surrounded by damp woodland"
  }, {
    "tag" : "identifier_affiliation",
    "value" : "University of Bath | University of Bath"
  }, {
    "tag" : "sex",
    "value" : "MALE"
  }, {
    "tag" : "symbiont",
    "value" : "N"
  }, {
    "tag" : "collecting institution",
    "value" : "University of Bath | University of Bath"
  }, {
    "tag" : "GAL",
    "value" : "Sanger Institute"
  }, {
    "tag" : "specimen_voucher",
    "value" : "NOT PROVIDED"
  }, {
    "tag" : "specimen_id",
    "value" : "SAN00002644"
  }, {
    "tag" : "GAL_sample_id",
    "value" : "NOT PROVIDED"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000053
/SAMEA110328947.json
{
  "alias" : "23447",
  "accession" : "ERS12426031",
  "centerName" : "Tree of Life Programme",
  "title" : "23447-tol",
  "organism" : {
    "taxonId" : "6319",
    "scientificName" : "Trichostrongylus colubriformis"
  },
  "attributes" : [ {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000053"
  }, {
    "tag" : "organism part",
    "value" : "WHOLE ORGANISM"
  }, {
    "tag" : "lifestage",
    "value" : "adult"
  }, {
    "tag" : "project name",
    "value" : "SAG_000101"
  }, {
    "tag" : "tolid",
    "value" : "nxTriColu2"
  }, {
    "tag" : "collected_by",
    "value" : "DANIEL PRICE | PHIL STEELE"
  }, {
    "tag" : "collection date",
    "value" : "2022-03-28"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "United Kingdom"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "55.856",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "-3.195",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (region and locality)",
    "value" : "Penicuik | Bush Loan | Moredun Research Institute | Farm"
  }, {
    "tag" : "identified_by",
    "value" : "DANIEL PRICE | PHIL STEELE"
  }, {
    "tag" : "habitat",
    "value" : "Ovine ileum"
  }, {
    "tag" : "identifier_affiliation",
    "value" : "MOREDUN RESEARCH INSTITUTE | MOREDUN RESEARCH INSTITUTE"
  }, {
    "tag" : "sample same as",
    "value" : "SAMEA110328935"
  }, {
    "tag" : "sex",
    "value" : "MALE"
  }, {
    "tag" : "symbiont",
    "value" : "N"
  }, {
    "tag" : "collecting institution",
    "value" : "MOREDUN RESEARCH INSTITUTE | MOREDUN RESEARCH INSTITUTE"
  }, {
    "tag" : "GAL",
    "value" : "Sanger Institute"
  }, {
    "tag" : "specimen_voucher",
    "value" : "NOT PROVIDED"
  }, {
    "tag" : "specimen_id",
    "value" : "SAN20001101"
  }, {
    "tag" : "GAL_sample_id",
    "value" : "SAN20001101"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000012
/SAMEA110292068.json
{
  "alias" : "20201119CLOUDK3",
  "accession" : "ERS12389676",
  "centerName" : "CNRS",
  "title" : "20201119CLOUDK3",
  "organism" : {
    "taxonId" : "256318",
    "scientificName" : "metagenome"
  },
  "attributes" : [ {
    "tag" : "air environmental package",
    "value" : "air"
  }, {
    "tag" : "collection date",
    "value" : "2020-11-19"
  }, {
    "tag" : "environment (biome)",
    "value" : "temperate forest"
  }, {
    "tag" : "environment (feature)",
    "value" : "mountain"
  }, {
    "tag" : "environment (material)",
    "value" : "water"
  }, {
    "tag" : "geographic location (altitude)",
    "value" : "1465",
    "unit" : "m"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "France"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "45.772",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "2.9655",
    "unit" : "DD"
  }, {
    "tag" : "investigation type",
    "value" : "metagenome"
  }, {
    "tag" : "project name",
    "value" : "Cloud-Air-16S"
  }, {
    "tag" : "sequencing method",
    "value" : "Illumina MiSeq"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000012"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000051
/SAMEA14398745.json
{
  "alias" : "LX32-9_rep1",
  "accession" : "ERS11998473",
  "centerName" : "Centrum Medyczne Ksztalcenia Podyplomowego",
  "title" : "LX32-9_rep1",
  "description" : "HCT116 overexpression BAZ",
  "organism" : {
    "taxonId" : "9606",
    "commonName" : "human",
    "scientificName" : "Homo sapiens"
  },
  "attributes" : [ {
    "tag" : "engrafted tumor sample passage",
    "value" : "32"
  }, {
    "tag" : "patient age at collection of tumor",
    "value" : "48"
  }, {
    "tag" : "patient sex",
    "value" : "Male"
  }, {
    "tag" : "patient tumor diagnosis at time of collection",
    "value" : "48"
  }, {
    "tag" : "patient tumor primary site",
    "value" : ""
  }, {
    "tag" : "patient tumor site of collection",
    "value" : ""
  }, {
    "tag" : "patient tumor type",
    "value" : "Primary Neoplasm"
  }, {
    "tag" : "sample material",
    "value" : "cell suspension"
  }, {
    "tag" : "sample origin",
    "value" : "Xenograft derived cell line"
  }, {
    "tag" : "sample taxon name",
    "value" : "Homo sapiens/Mus musculus xenograft"
  }, {
    "tag" : "sample unique ID",
    "value" : "LX32"
  }, {
    "tag" : "Was the PDX model humanised?",
    "value" : "No"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000051"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000034
/SAMEA4081140.json
{
  "alias" : "3342_19_14MCB140",
  "accession" : "ERS1252250",
  "centerName" : "NETHERLANDS CANCER INSTITUTE",
  "title" : "3342_19_14MCB140",
  "description" : "14MCB140 - spleen",
  "organism" : {
    "taxonId" : "10090",
    "commonName" : "house mouse",
    "scientificName" : "Mus musculus"
  },
  "attributes" : [ {
    "tag" : "diagnosis",
    "value" : "classic invasive lobular carcinoma"
  }, {
    "tag" : "sex",
    "value" : "female"
  }, {
    "tag" : "strain",
    "value" : "Wcre;Cdh1F/F;PtenF/F (FVB)"
  }, {
    "tag" : "tissue_type",
    "value" : "spleen"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000034"
  } ]
}
