=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000011-ENA.json
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "$id": "https://www.ebi.ac.uk/biosamples/schemas/ENA-ENA_default_sample_checklist/1.0.0",
  "title": "ENA default sample checklist",
  "description": "Minimum information required for the sample",
  "definitions": {
    "externalAccession": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "xrefLink": {
      "type": "object",
      "properties": {
        "db": {
          "type": "string"
        },
        "id": {
          "type": "string"
        }
      }
    },
    "urlLink": {
      "type": "object",
      "properties": {
        "label": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "identifiers": {
      "type": "object",
      "properties": {
        "externalAccessions": {
          "type": "array",
          "$ref": "#/definitions/externalAccession"
        },
        "secondaryAccessions": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "organism": {
      "type": "object",
      "properties": {
        "taxonId": {
          "type": "string"
        },
        "commonName": {
          "type": "string"
        },
        "scientificName": {
          "type": "string"
        },
        "anonymizedName": {
          "type": "string"
        },
        "individualName": {
          "type": "string"
        }
      }
    },
    "attribute": {
      "type": "object",
      "properties": {
        "tag": {
          "type": "string"
        },
        "value": {
          "type": "string"
        },
        "unit": {
          "type": "string"
        }
      }
    },
    "link": {
      "type": "object",
      "properties": {
        "xrefLink": {
          "$ref": "#/definitions/xrefLink"
        },
        "urlLink": {
          "$ref": "#/definitions/urlLink"
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "alias": {
      "type": "string"
    },
    "accession": {
      "type": "string"
    },
    "identifiers": {
      "$ref": "#/definitions/identifiers"
    },
    "centerName": {
      "type": "string"
    },
    "brokerName": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "organism": {
      "$ref": "#/definitions/organism"
    },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "tag": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }, "unit": {
            "type": "string"
          }
        },
        "additionalProperties": false,
        "required": [
          "tag",
          "value"
        ],
        "allOf": [
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "collection date"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "type": "string",
                  "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "tag": {
                  "enum": [
                    "geographic location"
                  ]
                }
              },
              "required": [
                "tag"
              ]
            },
            "then": {
              "properties": {
                "value": {
                  "enum": [
                    "UK",
                    "UGANDA"
                  ]
                }
              }
            }
          }
        ]
      },
      "allOf": [
        {
          "contains": {
            "type": "object",
            "description": "The date the sample was collected with the intention of sequencing, either as an instance (single point in time) or interval. In case no exact time is available, the date/time can be right truncated i.e. all of these are valid ISO8601 compliant times: 2008-01-23T19:23:10+00:00; 2008-01-23T19:23:10; 2008-01-23; 2008-01; 2008.",
            "properties": {
              "tag": {
                "enum": [
                  "collection date",
                  "Event Date/Time",
                  "collection_date"
                ]
              },
              "value": {
                "type": "string",
                "pattern": "(^[12][0-9]{3}(-(0[1-9]|1[0-2])(-(0[1-9]|[12][0-9]|3[01])(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?(/[0-9]{4}(-[0-9]{2}(-[0-9]{2}(T[0-9]{2}:[0-9]{2}(:[0-9]{2})?Z?([+-][0-9]{1,2})?)?)?)?)?$)|(^not collected$)|(^not provided$)|(^restricted access$)|(^missing: control sample$)|(^missing: sample group$)|(^missing: synthetic construct$)|(^missing: lab stock$)|(^missing: third party data$)|(^missing: data agreement established pre-2023$)|(^missing: endangered species$)|(^missing: human-identifiable$)"
              },
              "unit": {
                "type": "string"
              }
            },
            "required": [
              "tag",
              "value"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "tag": {
                "enum": [
                  "geographic location"
                ]
              }
            },
            "required": [
              "tag"
            ]
          },
          "then": {
            "properties": {
              "value": {
                "enum": [
                  "UK",
                  "UGANDA"
                ]
              },
              "unit": {
                "type": "string"
              }
            }
          }
        }
      ]
    },
    "links": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/link"
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "alias",
    "accession",
    "organism",
    "attributes"
  ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000018
/SAMEA12789639.json
{
  "alias" : "Sample_14",
  "accession" : "ERS10394985",
  "centerName" : "Perinatal laboratory at the Centre for Perinatal Medicine & Health",
  "title" : "Sample14",
  "description" : "Vaginal metatranscriptome preterm",
  "organism" : {
    "taxonId" : "1632839",
    "scientificName" : "human vaginal metagenome"
  },
  "attributes" : [ {
    "tag" : "collection date",
    "value" : "not provided"
  }, {
    "tag" : "environment (biome)",
    "value" : "human"
  }, {
    "tag" : "environment (feature)",
    "value" : "vagina"
  }, {
    "tag" : "environment (material)",
    "value" : "swab"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Sweden"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "57.708883",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "11.974573",
    "unit" : "DD"
  }, {
    "tag" : "human vaginal environmental package",
    "value" : "human-vaginal"
  }, {
    "tag" : "investigation type",
    "value" : "metatranscriptome"
  }, {
    "tag" : "project name",
    "value" : "Microbial transcriptome in vaginal fluid at midgestation: association with spontaneous preterm delivery"
  }, {
    "tag" : "sequencing method",
    "value" : "Illumina NovaSeq"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000018"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000036
/SAMEA10033095.json
{
  "alias" : "MQ210823-18",
  "accession" : "ERS7711299",
  "centerName" : "WDRC KAUST",
  "title" : "MABRbiofilm_cDNA_day30_control_feedWW_B1",
  "description" : "cDNA of control MABR biofilm-Reactor B1 fed with wastewater, sampled 9 March 2021",
  "organism" : {
    "taxonId" : "527639",
    "commonName" : "MABRbiofilm_cDNA_day30_control_feedWW_B1",
    "scientificName" : "wastewater metagenome"
  },
  "attributes" : [ {
    "tag" : "collection date",
    "value" : "2021-03-09"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Saudi Arabia"
  }, {
    "tag" : "investigation type",
    "value" : "metagenome"
  }, {
    "tag" : "sewage type",
    "value" : "Municipal wastewater treatment plant"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000036"
  } ]
}

=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000021/SAMEA7658988.json
{
  "alias": "L-CC-C2-1",
  "accession": "ERS5415995",
  "centerName": "University of Southampton",
  "title": "L-CC-C2-1",
  "description": "COI Control 2",
  "organism": {
    "taxonId": "256318",
    "scientificName": "metagenome"
  },
  "attributes": [
    {
      "tag": "collection date",
      "value": "2018-01-01"
    },
    {
      "tag": "environment (biome)",
      "value": "marine benthic"
    },
    {
      "tag": "environment (feature)",
      "value": "submarine canyon"
    },
    {
      "tag": "environment (material)",
      "value": "sediment"
    },
    {
      "tag": "geographic location (country and/or sea)",
      "value": "Mediterranean Sea"
    },
    {
      "tag": "geographic location (depth)",
      "value": "0",
      "unit": "m"
    },
    {
      "tag": "geographic location (elevation)",
      "value": "0",
      "unit": "m"
    },
    {
      "tag": "geographic location (latitude)",
      "value": "50.892",
      "unit": "DD"
    },
    {
      "tag": "geographic location (longitude)",
      "value": "-1.3942",
      "unit": "DD"
    },
    {
      "tag": "investigation type",
      "value": "metagenome"
    },
    {
      "tag": "project name",
      "value": "CC.19.LH"
    },
    {
      "tag": "sediment environmental package",
      "value": "sediment"
    },
    {
      "tag": "sequencing method",
      "value": "Illumina MiSeq"
    },
    {
      "tag": "ENA-CHECKLIST",
      "value": "ERC000021"
    }
  ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000034
/SAMEA4081124.json
{
  "alias" : "3342_08_14MCB140",
  "accession" : "ERS1252234",
  "centerName" : "NETHERLANDS CANCER INSTITUTE",
  "title" : "3342_08_14MCB140",
  "description" : "14MCB140 - ILC EpCAM",
  "organism" : {
    "taxonId" : "10090",
    "commonName" : "house mouse",
    "scientificName" : "Mus musculus"
  },
  "attributes" : [ {
    "tag" : "diagnosis",
    "value" : "classic invasive lobular carcinoma"
  }, {
    "tag" : "sex",
    "value" : "female"
  }, {
    "tag" : "strain",
    "value" : "Wcre;Cdh1F/F;PtenF/F (FVB)"
  }, {
    "tag" : "tissue_type",
    "value" : "mammary tumor"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000034"
  } ]
}

=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000014/SAMEA3401748.json
{
  "alias": "M13.3842",
  "accession": "ERS737888",
  "centerName": "Malawi College of Medicine",
  "title": "mlab",
  "description": "adult",
  "organism": {
    "taxonId": "1131769",
    "scientificName": "human nasal/pharyngeal metagenome"
  },
  "attributes": [
    {
      "tag": "investigation type",
      "value": "metagenome"
    },
    {
      "tag": "project name",
      "value": "Malawi nasopharyngeal microbiome"
    },
    {
      "tag": "sequencing method",
      "value": "pyrosequencing"
    },
    {
      "tag": "collection date",
      "value": "2003"
    },
    {
      "tag": "human-associated environmental package",
      "value": "human-associated"
    },
    {
      "tag": "geographic location (latitude)",
      "value": "-15.80127",
      "unit": "DD"
    },
    {
      "tag": "geographic location (longitude)",
      "value": "+35.021813",
      "unit": "DD"
    },
    {
      "tag": "geographic location (country and/or sea)",
      "value": "Malawi"
    },
    {
      "tag": "environment (biome)",
      "value": "head"
    },
    {
      "tag": "environment (feature)",
      "value": "nasal"
    },
    {
      "tag": "environment (material)",
      "value": "mucosal"
    },
    {
      "tag": "barcode_sequence",
      "value": "AGACCGTCAGAC"
    },
    {
      "tag": "linker_primer_sequence",
      "value": "CCGTCAATTCMTTTRAGT"
    },
    {
      "tag": "sample_area",
      "value": "null"
    },
    {
      "tag": "sample_age",
      "value": "null"
    },
    {
      "tag": "hiv_status",
      "value": "hivpos"
    },
    {
      "tag": "art_usage",
      "value": "null"
    },
    {
      "tag": "cd4_count-percentage",
      "value": "232"
    },
    {
      "tag": "pcv7_usage",
      "value": "PCV"
    },
    {
      "tag": "gender",
      "value": "null"
    },
    {
      "tag": "sampling_point",
      "value": "null"
    },
    {
      "tag": "description",
      "value": "Crossectional"
    },
    {
      "tag": "ENA-CHECKLIST",
      "value": "ERC000014"
    }
  ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000032
/SAMEA112177382.json
{
  "alias" : "19884916-f2a3-486c-ad92-b4f5549021f8",
  "accession" : "ERS14287222",
  "centerName" : "UNIVERSITY OF OXFORD",
  "title" : "Influenza genome sequencing",
  "organism" : {
    "taxonId" : "11320",
    "scientificName" : "Influenza A virus"
  },
  "attributes" : [ {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000032"
  }, {
    "tag" : "collection date",
    "value" : "2022-11"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "United Kingdom"
  }, {
    "tag" : "host common name",
    "value" : "human"
  }, {
    "tag" : "host subject id",
    "value" : "not collected"
  }, {
    "tag" : "host health state",
    "value" : "not collected"
  }, {
    "tag" : "host sex",
    "value" : "not collected"
  }, {
    "tag" : "host scientific name",
    "value" : "Homo sapien"
  }, {
    "tag" : "influenza test method",
    "value" : "RT-PCR"
  }, {
    "tag" : "influenza test result",
    "value" : "P"
  }, {
    "tag" : "other pathogens tested",
    "value" : "none"
  }, {
    "tag" : "other pathogens test result",
    "value" : "not applicable"
  }, {
    "tag" : "collector name",
    "value" : "Modernising Medical Microbiology"
  }, {
    "tag" : "collecting institution",
    "value" : "University of Oxford"
  } ]
}

=== ebi-ait/checklist-converter/data/samples/ERC000052
/SAMEA7025258.json
{
  "alias" : "CB05_02F1a_metaG",
  "accession" : "ERS4789468",
  "centerName" : "UNIVERSITY OF COPENHAGEN",
  "title" : "CB05.02F1a",
  "description" : "chicken MAG catalogue data from Caecum content; animal CB05.02 from cage CB05 with treatment CO",
  "organism" : {
    "taxonId" : "506600",
    "scientificName" : "chicken gut metagenome"
  },
  "attributes" : [ {
    "tag" : "adapters",
    "value" : "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA;GAACGACATGGCTACGATCCGACTT"
  }, {
    "tag" : "collection date",
    "value" : "2019-05-06"
  }, {
    "tag" : "geographic location (country and/or sea)",
    "value" : "Spain"
  }, {
    "tag" : "geographic location (latitude)",
    "value" : "41.170047",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (longitude)",
    "value" : "1.168491",
    "unit" : "DD"
  }, {
    "tag" : "geographic location (region and locality)",
    "value" : "El Morell; Tarragona"
  }, {
    "tag" : "host body site",
    "value" : "Caecum content"
  }, {
    "tag" : "host breed",
    "value" : "Ross"
  }, {
    "tag" : "host common name",
    "value" : "Chicken"
  }, {
    "tag" : "host diet",
    "value" : "unknown"
  }, {
    "tag" : "host diet treatment",
    "value" : "Probiotic"
  }, {
    "tag" : "host disease status",
    "value" : "N/A"
  }, {
    "tag" : "host scientific name",
    "value" : "Gallus gallus"
  }, {
    "tag" : "host sex",
    "value" : "female"
  }, {
    "tag" : "host subject id",
    "value" : "CB05.02"
  }, {
    "tag" : "host taxid",
    "value" : "9031"
  }, {
    "tag" : "host total mass",
    "value" : "172.50",
    "unit" : "g"
  }, {
    "tag" : "nucleic acid extraction",
    "value" : "D-rex protocol"
  }, {
    "tag" : "pcr primers",
    "value" : "N/A"
  }, {
    "tag" : "project name",
    "value" : "HoloFood Chicken - MAG Catalogue from Caecum content"
  }, {
    "tag" : "reference host genome for decontamination",
    "value" : "GCA_000000000.0"
  }, {
    "tag" : "sample storage buffer",
    "value" : "Shield"
  }, {
    "tag" : "sample storage container",
    "value" : "E-matrix 2ml"
  }, {
    "tag" : "sample storage location",
    "value" : "UCPH"
  }, {
    "tag" : "sample storage temperature",
    "value" : "-20",
    "unit" : "°C"
  }, {
    "tag" : "sample volume or weight for DNA extraction",
    "value" : "0.2",
    "unit" : "mL"
  }, {
    "tag" : "sequencing method",
    "value" : "MGISEQ-2000"
  }, {
    "tag" : "trial length",
    "value" : "35",
    "unit" : "days"
  }, {
    "tag" : "trial timepoint",
    "value" : "7",
    "unit" : "days"
  }, {
    "tag" : "host storage container temperature",
    "value" : "21",
    "unit" : "°C"
  }, {
    "tag" : "ENA-CHECKLIST",
    "value" : "ERC000052"
  } ]
}

=== ebi-ait/checklist-converter/src/test/resources/samples/ERC000022/SAMEA8579965.json
{
  "alias": "fun.nac371",
  "accession": "ERS6264623",
  "centerName": "Barta",
  "title": "fun_371",
  "description": "fungal ITS1",
  "organism": {
    "taxonId": "256318",
    "scientificName": "metagenome"
  },
  "attributes": [
    {
      "tag": "collection date",
      "value": "2013"
    },
    {
      "tag": "environment (biome)",
      "value": "spruce biome"
    },
    {
      "tag": "environment (feature)",
      "value": "spruce forest"
    },
    {
      "tag": "environment (material)",
      "value": "soil"
    },
    {
      "tag": "geographic location (country and/or sea)",
      "value": "Czech Republic"
    },
    {
      "tag": "geographic location (depth)",
      "value": "0.1",
      "unit": "m"
    },
    {
      "tag": "geographic location (elevation)",
      "value": "784",
      "unit": "m"
    },
    {
      "tag": "geographic location (latitude)",
      "value": "50.590556",
      "unit": "DD"
    },
    {
      "tag": "geographic location (longitude)",
      "value": "13.253889",
      "unit": "DD"
    },
    {
      "tag": "investigation type",
      "value": "metagenome"
    },
    {
      "tag": "project name",
      "value": "Nacetin13"
    },
    {
      "tag": "sequencing method",
      "value": "Illumina MiSeq"
    },
    {
      "tag": "soil environmental package",
      "value": "soil"
    },
    {
      "tag": "ENA-CHECKLIST",
      "value": "ERC000022"
    }
  ]
}
